name: mic-loader
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - boto3=1.8.2
  - botocore=1.11.2
  - docutils=0.14
  - jmespath=0.9.3
  - s3transfer=0.1.13
  - asn1crypto=0.24.0
  - ca-certificates=2018.8.24
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.3
  - cryptography-vectors=2.3
  - idna=2.7
  - nose=1.3.7
  - openssl=1.0.2p
  - pandas=0.23.4
  - pip=18.0
  - pycparser=2.18
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - python=3.7.0
  - python-dateutil=2.7.3
  - pytz=2018.5
  - requests=2.19.1
  - setuptools=40.2.0
  - six=1.11.0
  - urllib3=1.23
  - wheel=0.31.1
  - xlrd=1.1.0
  - blas=1.0=mkl
  - icc_rt=2017.0.4
  - intel-openmp=2018.0.3=0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - numpy=1.15.1
  - numpy-base=1.15.1
  - win_inet_pton=1.0.1
